---
- hosts: localhost
  tasks:
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
   - pause:
       seconds: 5
 
